# Generated by Django 2.2.28 on 2022-12-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=256)),
                ('expiry_date_month', models.IntegerField()),
                ('expiry_date_year', models.IntegerField()),
                ('security_code', models.IntegerField()),
                ('card_holder_name', models.CharField(max_length=256)),
                ('stripe_id', models.CharField(blank=True, max_length=256, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('media', models.FileField(upload_to='plans_media/')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=256)),
                ('short_name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('sub_type', models.CharField(blank=True, choices=[('Billed Monthly', 'Billed Monthly'), ('Billed Yearly', 'Billed Yearly')], max_length=256, null=True)),
                ('duration', models.IntegerField()),
                ('duration_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=256, null=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=256, null=True)),
                ('apple_product_id', models.CharField(blank=True, max_length=256, null=True)),
                ('plan_media', models.ManyToManyField(to='membership.SubscriptionMedia')),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_stripe_active', models.BooleanField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_sub_id', models.CharField(blank=True, max_length=256, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.SubscriptionPlan')),
            ],
        ),
    ]
