# Generated by Django 2.2.24 on 2022-11-11 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_meals', to='meals.MealCategory'),
        ),
        migrations.AddField(
            model_name='meal',
            name='filters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_meals', to='meals.MealFilter'),
        ),
    ]
