# Generated by Django 2.2.24 on 2022-11-11 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20221111_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meal_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
