# Generated by Django 2.2.24 on 2022-11-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20221111_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='plan_calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='plan_carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='plan_fats',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='plan_protein',
            field=models.FloatField(default=0),
        ),
    ]
