# Generated by Django 2.2.28 on 2022-11-12 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0004_auto_20221111_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_completed', to='meals.Meal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
