# Generated by Django 2.2.28 on 2023-07-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_mealcompletion_meal_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealinstruction',
            name='video_start_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
