# Generated by Django 2.2.28 on 2022-11-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylevel',
            name='value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
