# Generated by Django 2.2.28 on 2023-08-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20230327_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='deviation_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
