# Generated by Django 2.2.28 on 2022-12-11 17:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('internal_name', models.CharField(blank=True, max_length=256, null=True)),
                ('rounds', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('poster', models.FileField(blank=True, null=True, upload_to='exercise_posters/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'mp4'])])),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='exercises_media/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'mp4'])])),
                ('is_media_video', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('week_number', models.IntegerField()),
                ('friday_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday_workouts', to='workouts.DayWorkout')),
                ('monday_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday_workouts', to='workouts.DayWorkout')),
                ('saturday_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_workouts', to='workouts.DayWorkout')),
                ('sunday_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_workouts', to='workouts.DayWorkout')),
                ('thursday_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_workouts', to='workouts.DayWorkout')),
                ('tuesday_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_workouts', to='workouts.DayWorkout')),
                ('wednesday_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_workouts', to='workouts.DayWorkout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('seconds', models.IntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Exercise')),
            ],
        ),
        migrations.RemoveField(
            model_name='workoutmedia',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='workoutsubscription',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='workoutsubscription',
            name='workout',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.DeleteModel(
            name='WorkoutCategory',
        ),
        migrations.DeleteModel(
            name='WorkoutMedia',
        ),
        migrations.DeleteModel(
            name='WorkoutSubscription',
        ),
        migrations.AddField(
            model_name='program',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='workouts.ProgramWeek'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.ExerciseCategory'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_media',
            field=models.ManyToManyField(to='workouts.ExerciseMedia'),
        ),
        migrations.AddField(
            model_name='dayworkout',
            name='workout_items',
            field=models.ManyToManyField(blank=True, to='workouts.WorkoutItem'),
        ),
    ]
