# Generated by Django 2.2.28 on 2022-12-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20221211_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.Exercise'),
        ),
    ]
