# Generated by Django 2.2.28 on 2022-12-11 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20221122_2209'),
        ('workouts', '0004_exercise_substitute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Goal')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Program')),
                ('training_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.TrainingFor')),
                ('workout_availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.WorkoutAvailability')),
            ],
        ),
    ]
