# Generated by Django 2.2.28 on 2022-12-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_programanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to='program_pdf/'),
        ),
    ]
