# Generated by Django 2.2.28 on 2022-12-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_workoutrating_workoutsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutrating',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='workoutsubscription',
            name='workout_date',
        ),
    ]
