# Generated by Django 2.2.28 on 2023-06-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_auto_20230213_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsubscription',
            name='day',
        ),
        migrations.RemoveField(
            model_name='workoutsubscription',
            name='week_number',
        ),
        migrations.AlterField(
            model_name='workoutsubscription',
            name='is_complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
