# Generated by Django 2.2.28 on 2022-12-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('users', '0005_auto_20221111_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_membership', to='membership.UserMembership'),
        ),
        migrations.AddField(
            model_name='user',
            name='memberships',
            field=models.ManyToManyField(blank=True, to='membership.UserMembership'),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_cards',
            field=models.ManyToManyField(blank=True, to='membership.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_method_user', to='membership.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_cust_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
