# Generated by Django 2.2.28 on 2022-12-16 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_program_pdf_document'),
        ('users', '0006_auto_20221202_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workout_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.Program'),
        ),
    ]
